// SPDX-License-Identifier: GPL-3.0-or-later
package gg.tame.conduit.protocol.item;

import gg.tame.conduit.protocol.ProtocolEras;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalInt;

/**
 * Item identity for every protocol Conduit speaks.
 *
 * <p>Both the name tables and the id translation tables are generated by
 * {@code tools/gen_mappings.py} and {@code tools/gen_mappings_pair.py} from the
 * reports the official server jars emit about themselves ({@code --reports}).
 * Every cross-version mapping was resolved by item <em>name</em>; the numeric
 * tables are only a materialised index of that name resolution, never id
 * arithmetic.
 *
 * <p>Each protocol gets its <em>own</em> registry. That is not pedantry: 1.13.1
 * inserted the dead-coral items at id 443, so 347 of 1.13's 785 item ids mean
 * something different in 1.13.2, and 1.14 shifted 678 of 1.13.2's 790. Treating
 * "everything before 1.16" as one flattening table — as this class previously
 * did — hands the player the wrong item for most of the registry.
 *
 * <p>An id with no counterpart returns empty. Callers must fail closed — showing
 * the player nothing is correct where showing them a different item is not.
 */
public final class ItemRegistries {
  /** Protocols with a dedicated, generated item registry. */
  private static final int[] REGISTRIES = { 393, 404, 477, 765 };

  private static final Map<Integer, List<String>> NAMES = loadAllNames();
  private static final Map<Integer, Map<String, Integer>> IDS = indexAll(NAMES);
  private static final Map<Long, int[]> TABLES = loadAllTables();

  private ItemRegistries() {}

  /**
   * The registry version a protocol speaks.
   *
   * <p>Explicit per protocol rather than a {@code < 735} bucket. Zero means "no
   * registry modelled", and every lookup then fails closed instead of guessing.
   */
  private static int registry(int protocol) {
    if (protocol == 393 || protocol == 404 || protocol == 477) return protocol;
    if (ProtocolEras.joinGameRegistry(protocol)) return 765;   // 1.16+ share the 765 table here
    return 0;
  }

  /** The identifier this protocol gives that numeric item id, if it has one. */
  public static Optional<String> name(int protocol, int id) {
    List<String> names = NAMES.get(registry(protocol));
    if (names == null || id < 0 || id >= names.size()) return Optional.empty();
    String name = names.get(id);
    return name.isEmpty() ? Optional.empty() : Optional.of(name);
  }

  /** The numeric id this protocol gives that identifier, if it has one. */
  public static OptionalInt id(int protocol, String name) {
    Map<String, Integer> ids = IDS.get(registry(protocol));
    if (ids == null) return OptionalInt.empty();
    Integer id = ids.get(name);
    return id == null ? OptionalInt.empty() : OptionalInt.of(id);
  }

  /**
   * Translates a numeric item id across a pair, by name.
   *
   * <p>Empty when the pair has no generated table or the item has no counterpart.
   * There is deliberately no numeric-passthrough fallback: the ids that survive a
   * version boundary unchanged are a minority, so passthrough is not a
   * conservative approximation, it is a wrong answer for most of the registry.
   */
  public static OptionalInt translate(int fromProtocol, int toProtocol, int id) {
    if (fromProtocol == toProtocol) return OptionalInt.of(id);
    int from = registry(fromProtocol);
    int to = registry(toProtocol);
    if (from == 0 || to == 0) return OptionalInt.empty();
    if (from == to) return OptionalInt.of(id);
    int[] table = TABLES.get(key(from, to));
    if (table == null || id < 0 || id >= table.length) return OptionalInt.empty();
    int mapped = table[id];
    return mapped < 0 ? OptionalInt.empty() : OptionalInt.of(mapped);
  }

  public static int size(int protocol) {
    List<String> names = NAMES.get(registry(protocol));
    return names == null ? 0 : names.size();
  }

  private static long key(int from, int to) {
    return ((long) from << 32) | (to & 0xffffffffL);
  }

  private static Map<Integer, List<String>> loadAllNames() {
    Map<Integer, List<String>> names = new HashMap<>();
    for (int protocol : REGISTRIES) {
      names.put(protocol, loadNames("items_" + protocol + "_names.txt"));
    }
    return Map.copyOf(names);
  }

  private static Map<Integer, Map<String, Integer>> indexAll(Map<Integer, List<String>> names) {
    Map<Integer, Map<String, Integer>> ids = new HashMap<>();
    names.forEach((protocol, list) -> ids.put(protocol, index(list)));
    return Map.copyOf(ids);
  }

  /**
   * The generated pair tables. Only pairs Conduit actually translates between
   * are present; anything else resolves to empty rather than to a guess.
   */
  private static Map<Long, int[]> loadAllTables() {
    int[][] pairs = { { 393, 404 }, { 404, 477 }, { 393, 765 } };
    Map<Long, int[]> tables = new HashMap<>();
    for (int[] pair : pairs) {
      tables.put(key(pair[0], pair[1]), loadTable("items_" + pair[0] + "_to_" + pair[1] + ".bin"));
      tables.put(key(pair[1], pair[0]), loadTable("items_" + pair[1] + "_to_" + pair[0] + ".bin"));
    }
    return Map.copyOf(tables);
  }

  private static Map<String, Integer> index(List<String> names) {
    Map<String, Integer> ids = new HashMap<>(names.size() * 2);
    for (int id = 0; id < names.size(); id++) {
      String name = names.get(id);
      if (!name.isEmpty()) ids.put(name, id);
    }
    return Map.copyOf(ids);
  }

  private static List<String> loadNames(String resource) {
    String path = "/gg/tame/conduit/protocol/item/" + resource;
    try (InputStream in = ItemRegistries.class.getResourceAsStream(path)) {
      if (in == null) throw new IllegalStateException("missing resource " + path);
      List<String> names = new ArrayList<>();
      BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
      String line;
      while ((line = reader.readLine()) != null) names.add(line.trim());
      return List.copyOf(names);
    } catch (IOException exception) {
      throw new IllegalStateException("cannot load " + resource, exception);
    }
  }

  private static int[] loadTable(String resource) {
    String path = "/gg/tame/conduit/protocol/item/" + resource;
    try (InputStream in = ItemRegistries.class.getResourceAsStream(path)) {
      if (in == null) throw new IllegalStateException("missing resource " + path);
      byte[] header = in.readNBytes(4);
      if (header.length != 4) throw new IllegalStateException("truncated " + resource);
      int length = (header[0] & 0xff) | ((header[1] & 0xff) << 8)
          | ((header[2] & 0xff) << 16) | ((header[3] & 0xff) << 24);
      if (length < 1 || length > 100_000) throw new IllegalStateException("bad length " + length);
      byte[] body = in.readNBytes(length * 4);
      if (body.length != length * 4) throw new IllegalStateException("truncated body " + resource);
      int[] table = new int[length];
      for (int index = 0; index < length; index++) {
        int offset = index * 4;
        table[index] = (body[offset] & 0xff) | ((body[offset + 1] & 0xff) << 8)
            | ((body[offset + 2] & 0xff) << 16) | ((body[offset + 3] & 0xff) << 24);
      }
      return table;
    } catch (IOException exception) {
      throw new IllegalStateException("cannot load " + resource, exception);
    }
  }
}
