package gg.tame.conduit.protocol.item;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalInt;

/**
 * Item identity for protocol 393 (1.13) and 765 (1.20.4).
 *
 * <p>Both the name tables and the id translation tables are generated by
 * {@code tools/gen_mappings.py} from the reports the official server jars emit
 * about themselves ({@code --reports}). Every cross-version mapping was resolved
 * by item <em>name</em>; the numeric tables are only a materialised index of
 * that name resolution, never id arithmetic.
 *
 * <p>An id with no counterpart returns empty. Callers must fail closed — showing
 * the player nothing is correct where showing them a different item is not.
 */
public final class ItemRegistries {
  private static final List<String> NAMES_393 = loadNames("items_393_names.txt");
  private static final List<String> NAMES_765 = loadNames("items_765_names.txt");
  private static final Map<String, Integer> IDS_393 = index(NAMES_393);
  private static final Map<String, Integer> IDS_765 = index(NAMES_765);
  private static final int[] TO_765 = loadTable("items_393_to_765.bin");
  private static final int[] TO_393 = loadTable("items_765_to_393.bin");

  private ItemRegistries() {}

  /** The identifier this protocol gives that numeric item id, if it has one. */
  public static Optional<String> name(int protocol, int id) {
    List<String> names = protocol <= 404 ? NAMES_393 : NAMES_765;
    if (id < 0 || id >= names.size()) return Optional.empty();
    String name = names.get(id);
    return name.isEmpty() ? Optional.empty() : Optional.of(name);
  }

  /** The numeric id this protocol gives that identifier, if it has one. */
  public static OptionalInt id(int protocol, String name) {
    Integer id = (protocol <= 404 ? IDS_393 : IDS_765).get(name);
    return id == null ? OptionalInt.empty() : OptionalInt.of(id);
  }

  /** Translates a numeric item id across the pair, by name. Empty when unmapped. */
  public static OptionalInt translate(int fromProtocol, int toProtocol, int id) {
    if (fromProtocol == toProtocol) return OptionalInt.of(id);
    int[] table = toProtocol <= 404 ? TO_393 : TO_765;
    if (id < 0 || id >= table.length) return OptionalInt.empty();
    int mapped = table[id];
    return mapped < 0 ? OptionalInt.empty() : OptionalInt.of(mapped);
  }

  public static int size(int protocol) {
    return (protocol <= 404 ? NAMES_393 : NAMES_765).size();
  }

  private static Map<String, Integer> index(List<String> names) {
    Map<String, Integer> ids = new HashMap<>(names.size() * 2);
    for (int id = 0; id < names.size(); id++) {
      String name = names.get(id);
      if (!name.isEmpty()) ids.put(name, id);
    }
    return Map.copyOf(ids);
  }

  private static List<String> loadNames(String resource) {
    String path = "/gg/tame/conduit/protocol/item/" + resource;
    try (InputStream in = ItemRegistries.class.getResourceAsStream(path)) {
      if (in == null) throw new IllegalStateException("missing resource " + path);
      List<String> names = new ArrayList<>();
      BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
      String line;
      while ((line = reader.readLine()) != null) names.add(line.trim());
      return List.copyOf(names);
    } catch (IOException exception) {
      throw new IllegalStateException("cannot load " + resource, exception);
    }
  }

  private static int[] loadTable(String resource) {
    String path = "/gg/tame/conduit/protocol/item/" + resource;
    try (InputStream in = ItemRegistries.class.getResourceAsStream(path)) {
      if (in == null) throw new IllegalStateException("missing resource " + path);
      byte[] header = in.readNBytes(4);
      if (header.length != 4) throw new IllegalStateException("truncated " + resource);
      int length = (header[0] & 0xff) | ((header[1] & 0xff) << 8)
          | ((header[2] & 0xff) << 16) | ((header[3] & 0xff) << 24);
      if (length < 1 || length > 100_000) throw new IllegalStateException("bad length " + length);
      byte[] body = in.readNBytes(length * 4);
      if (body.length != length * 4) throw new IllegalStateException("truncated body " + resource);
      int[] table = new int[length];
      for (int index = 0; index < length; index++) {
        int offset = index * 4;
        table[index] = (body[offset] & 0xff) | ((body[offset + 1] & 0xff) << 8)
            | ((body[offset + 2] & 0xff) << 16) | ((body[offset + 3] & 0xff) << 24);
      }
      return table;
    } catch (IOException exception) {
      throw new IllegalStateException("cannot load " + resource, exception);
    }
  }
}
