package gg.tame.conduit.protocol;

public enum PacketKind {
  HANDSHAKE, STATUS_REQUEST, STATUS_PING, LOGIN_START, LOGIN_SUCCESS, LOGIN_DISCONNECT,
  LOGIN_ENCRYPTION_REQUEST, LOGIN_ENCRYPTION_RESPONSE, LOGIN_SET_COMPRESSION, LOGIN_PLUGIN_REQUEST, LOGIN_PLUGIN_RESPONSE,
  LOGIN_ACKNOWLEDGED, CONFIGURATION_FINISH, PLAY_LOGIN
}
