package gg.tame.conduit.protocol;

public enum PacketKind {
  HANDSHAKE, STATUS_REQUEST, STATUS_PING, LOGIN_START, LOGIN_SUCCESS, LOGIN_DISCONNECT,
  LOGIN_ENCRYPTION_REQUEST, LOGIN_ENCRYPTION_RESPONSE, LOGIN_SET_COMPRESSION, LOGIN_PLUGIN_REQUEST, LOGIN_PLUGIN_RESPONSE,
  LOGIN_ACKNOWLEDGED, CONFIGURATION_FINISH, CONFIGURATION_PLUGIN_MESSAGE, CONFIGURATION_KNOWN_PACKS, CONFIGURATION_REGISTRY, CONFIGURATION_RESET_CHAT,
  CONFIGURATION_DISCONNECT, CONFIGURATION_KEEP_ALIVE,
  PLAY_LOGIN, PLAY_PLUGIN_MESSAGE, PLAY_START_CONFIGURATION, PLAY_SYSTEM_CHAT,
  PLAY_TAB_COMPLETE, PLAY_DISCONNECT, PLAY_CHAT_COMMAND, PLAY_TAB_COMPLETE_REQUEST,
  PLAY_CONFIGURATION_ACKNOWLEDGED, PLAY_DECLARE_COMMANDS, PLAY_PLAYER_INFO_UPDATE, PLAY_PLAYER_INFO_REMOVE,
  PLAY_CLIENT_INFORMATION, CONFIGURATION_CLIENT_INFORMATION
}
