#!/usr/bin/env python3
"""Generate ProtocolRevisions.java -- the delta table that scales Conduit's
packet registry across 1.13-26.2 without one hand-copied table per protocol.

Each revision derives from the nearest already-registered protocol and lists
only the packet ids that release actually moved, added or removed. Ids come
from tools/packetids.py, i.e. from published packet data, cross-checked against
Conduit's own hand-authored tables by `packetids.py check`.

Capabilities are inherited from the base version and are explicitly NOT audited
per release; that is what CodecStatus.DERIVED means. Promoting a protocol past
DERIVED requires auditing its capabilities and exercising it on the wire.
"""

from __future__ import annotations

from pathlib import Path

import packetids

OUT = Path(__file__).resolve().parent.parent / \
    "src/main/java/gg/tame/conduit/protocol/ProtocolRevisions.java"

# (protocol, release, base protocol, base release, ProtocolVersion constant).
# The chain walks forward through the pre-configuration era from the declared
# 1.13 table, then hangs the configuration-era releases off the declared 1.20.4
# and 1.20.5 tables, which are the richest declared tables Conduit has.
CHAIN = [
    (401, "1.13.1", 393, "1.13", "MINECRAFT_1_13_1"),
    (404, "1.13.2", 401, "1.13.1", "MINECRAFT_1_13_2"),
    (477, "1.14", 404, "1.13.2", "MINECRAFT_1_14"),
    (480, "1.14.1", 477, "1.14", "MINECRAFT_1_14_1"),
    (485, "1.14.2", 480, "1.14.1", "MINECRAFT_1_14_2"),
    (490, "1.14.3", 485, "1.14.2", "MINECRAFT_1_14_3"),
    (498, "1.14.4", 490, "1.14.3", "MINECRAFT_1_14_4"),
    (573, "1.15", 498, "1.14.4", "MINECRAFT_1_15"),
    (575, "1.15.1", 573, "1.15", "MINECRAFT_1_15_1"),
    (578, "1.15.2", 575, "1.15.1", "MINECRAFT_1_15_2"),
    (735, "1.16", 578, "1.15.2", "MINECRAFT_1_16"),
    (736, "1.16.1", 735, "1.16", "MINECRAFT_1_16_1"),
    (751, "1.16.2", 736, "1.16.1", "MINECRAFT_1_16_2"),
    (753, "1.16.3", 751, "1.16.2", "MINECRAFT_1_16_3"),
    (754, "1.16.5", 753, "1.16.3", "MINECRAFT_1_16_5"),
    (755, "1.17", 754, "1.16.5", "MINECRAFT_1_17"),
    (756, "1.17.1", 755, "1.17", "MINECRAFT_1_17_1"),
    (757, "1.18", 756, "1.17.1", "MINECRAFT_1_18"),
    (758, "1.18.2", 757, "1.18", "MINECRAFT_1_18_2"),
    (759, "1.19", 758, "1.18.2", "MINECRAFT_1_19"),
    (760, "1.19.2", 759, "1.19", "MINECRAFT_1_19_2"),
    (761, "1.19.3", 760, "1.19.2", "MINECRAFT_1_19_3"),
    (762, "1.19.4", 761, "1.19.3", "MINECRAFT_1_19_4"),
    # 1.20.2 introduced the configuration state. Derive it from the declared
    # 1.20.4 table rather than from 1.20.1, which predates configuration
    # entirely and would leave every configuration-state packet absent.
    (764, "1.20.2", 765, "1.20.4", "MINECRAFT_1_20_2"),
    # Base 1.21 on the declared 1.20.4 table, not on 1.20.5/1.20.6. The declared
    # 766 table covers only login/configuration and a handful of play packets,
    # so deriving from it would propagate that gap forward through the whole
    # 1.21 and 26.x chain. 765 is the richest declared table Conduit has.
    (767, "1.21", 765, "1.20.4", "MINECRAFT_1_21"),
    (768, "1.21.3", 767, "1.21", "MINECRAFT_1_21_3"),
    (769, "1.21.4", 768, "1.21.3", "MINECRAFT_1_21_4"),
    (770, "1.21.5", 769, "1.21.4", "MINECRAFT_1_21_5"),
    (771, "1.21.6", 770, "1.21.5", "MINECRAFT_1_21_6"),
    (772, "1.21.8", 771, "1.21.6", "MINECRAFT_1_21_8"),
    (773, "1.21.10", 772, "1.21.8", "MINECRAFT_1_21_10"),
    (774, "1.21.11", 773, "1.21.10", "MINECRAFT_1_21_11"),
    (775, "26.1", 774, "1.21.11", "MINECRAFT_26_1"),
]

HEADER = '''package gg.tame.conduit.protocol;

import java.util.List;

/**
 * Per-version packet-id deltas for the 1.13&ndash;26.2 compatibility program.
 *
 * <p>GENERATED by {@code tools/gen_revisions.py}; do not hand-edit. Regenerate
 * after changing the kind mapping in {@code tools/packetids.py}, and run
 * {@code python tools/packetids.py check} to confirm the generated ids still
 * agree with Conduit's hand-authored 1.13 / 1.20.1 / 1.20.4 / 1.20.5 tables.
 *
 * <p>Each entry derives from the nearest already-registered protocol and lists
 * only the mappings that release changed, so adding a Minecraft version costs
 * roughly what the version actually changed rather than a full transcribed
 * packet table. Numeric ids belong to the protocol; translators address packets
 * by {@link PacketKind} and never compute a target id from a source id.
 *
 * <p>Every entry here is {@link CodecStatus#DERIVED}: its ids trace to published
 * packet data, but this exact protocol number has not been audited packet by
 * packet, and its capabilities are inherited from its base version rather than
 * confirmed against the release. That is a usable codec, not a support claim
 * &mdash; see {@link CompatibilityRegistry} for what Conduit will actually carry.
 */
public final class ProtocolRevisions {
  private ProtocolRevisions() {}

'''


def java_capabilities(protocol: int) -> str:
    """Capabilities for a derived revision.

    Inheriting the base version's capabilities (null) is right almost
    everywhere, but the 1.21+ chain is derived from the declared 1.20.4 table
    for packet-id coverage, and 1.20.4 predates the known-packs, cookie and
    transfer packets that 1.20.5 introduced and every later version keeps.
    Inheriting there would understate what those versions can do, so state it.
    """
    if protocol >= 766:
        # configuration, loginShouldAuthenticate, knownPacks, joinGameOnlineMode,
        # cookiePackets, transferPackets, chatSigning, secureChat
        return "new ProtocolCapabilities(true, false, true, false, true, true, true, true)"
    return "null"  # inherit the base definition's capabilities; resolved in derive()


def main() -> None:
    blocks = []
    names = []
    # The chain's nominal base may itself have no published data, in which case
    # we re-base onto the most recent protocol this run actually registered.
    # Registered anchors start with Conduit's declared tables.
    registered = {393: "1.13", 763: "1.20.1", 765: "1.20.4", 766: "1.20.6"}
    for protocol, release, base_protocol, base_release, constant in CHAIN:
        if packetids.protocol_json(release) is None:
            print(f"[skip] {release}: no published protocol.json; later versions re-base")
            continue
        if base_protocol not in registered:
            previous = max(p for p in registered if p < protocol)
            print(f"       {release}: base {base_protocol} unavailable, re-basing on {previous}")
            base_protocol, base_release = previous, registered[previous]
        base_table = packetids.table_for(base_release)
        target_table = packetids.table_for(release)
        deltas = []
        for key in sorted(set(base_table) | set(target_table)):
            old, new = base_table.get(key), target_table.get(key)
            if old == new:
                continue
            state, direction, kind = key
            js = packetids.JAVA_STATE[state]
            jd = packetids.JAVA_DIRECTION[direction]
            if new is None:
                deltas.append(f"          PacketMapping.removed(ConnectionState.{js}, "
                              f"PacketDirection.{jd}, PacketKind.{kind})")
            else:
                deltas.append(f"          PacketMapping.of(ConnectionState.{js}, "
                              f"PacketDirection.{jd}, PacketKind.{kind}, 0x{new:02X})")
        field = f"V{release.replace('.', '_')}"
        names.append(field)
        registered[protocol] = release
        body = ",\n".join(deltas) if deltas else ""
        blocks.append(f'''  /** {release} (protocol {protocol}), derived from {base_release} (protocol {base_protocol}): {len(deltas)} changed mappings. */
  public static final ProtocolRevision {field} = new ProtocolRevision(
      ProtocolVersion.{constant},
      {base_protocol},
      {java_capabilities(protocol)},
      CodecStatus.DERIVED,
      "published packet ids for {release}; capabilities inherited from {base_release}",
      List.of(
{body}));
''')
        print(f"{release:<10} proto {protocol:<4} base {base_protocol:<4} {len(deltas):>3} deltas")

    listing = ",\n      ".join(names)
    text = HEADER + "\n".join(blocks) + f'''
  /**
   * Registration order matters: a revision may derive from a protocol that an
   * earlier revision in this list introduced, so the chain must stay ordered.
   */
  public static final List<ProtocolRevision> ALL = List.of(
      {listing});
}}
'''
    OUT.write_text(text, encoding="utf-8")
    print(f"\nwrote {OUT} ({len(names)} revisions)")


if __name__ == "__main__":
    main()
