// SPDX-License-Identifier: GPL-3.0-or-later
package gg.tame.conduit.protocol.sound;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalInt;

/**
 * Sound-event identity for the protocols Conduit translates sounds between.
 *
 * <p>A sound travels as a registry index, and the registries disagree: 1.13 has
 * 662 sound events and 1.20.4 has 1539, with the additions spread through the
 * list rather than appended. So an index means a different sound on each side,
 * and forwarding it plays the wrong one — which is why sounds were dropped
 * outright before this table existed.
 *
 * <p>The tables are generated by {@code tools/gen_sounds.py} from Mojang's own
 * registries: 1.20.4's from the server's {@code --reports} dump, 1.13's read out
 * of its jar because its reports predate that dump. Every mapping is resolved by
 * sound <em>name</em>; the numeric tables are a materialised index of that name
 * resolution, never id arithmetic. The generator refuses to emit a table whose
 * 1.13 order does not agree with an independent later registry.
 *
 * <p>Four of 1.13's sounds have no 1.20.4 counterpart (three parrot imitations
 * removed in 1.14, and the zombie pigman imitation, which did not return under
 * the piglin name). They map to empty and the caller drops that one packet, as
 * every sound used to be dropped.
 */
public final class SoundRegistries {
  /** Protocols with a dedicated, generated sound registry. */
  private static final int[] REGISTRIES = { 393, 765 };

  private static final Map<Integer, List<String>> NAMES = loadAllNames();
  private static final Map<Integer, Map<String, Integer>> IDS = indexAll(NAMES);
  private static final Map<Long, int[]> TABLES = loadAllTables();

  private SoundRegistries() {}

  /**
   * The registry version a protocol speaks, or zero when none is modelled.
   *
   * <p>Deliberately exact rather than a range. A protocol between these two has
   * its own registry that Conduit has not generated, and answering with either
   * of these would be a wrong sound rather than a near one, so it gets nothing
   * and the caller drops the packet.
   */
  private static int registry(int protocol) {
    return protocol == 393 || protocol == 765 ? protocol : 0;
  }

  /** Whether sounds can be translated across this ordered pair at all. */
  public static boolean translates(int fromProtocol, int toProtocol) {
    int from = registry(fromProtocol);
    int to = registry(toProtocol);
    return from != 0 && to != 0;
  }

  /** The identifier this protocol gives that numeric sound id, if it has one. */
  public static Optional<String> name(int protocol, int id) {
    List<String> names = NAMES.get(registry(protocol));
    if (names == null || id < 0 || id >= names.size()) return Optional.empty();
    String name = names.get(id);
    return name.isEmpty() ? Optional.empty() : Optional.of(name);
  }

  /** The numeric id this protocol gives that identifier, if it has one. */
  public static OptionalInt id(int protocol, String name) {
    Map<String, Integer> ids = IDS.get(registry(protocol));
    if (ids == null) return OptionalInt.empty();
    Integer id = ids.get(name);
    return id == null ? OptionalInt.empty() : OptionalInt.of(id);
  }

  /**
   * Translates a numeric sound id across a pair, by name.
   *
   * <p>Empty when the pair has no generated table or the sound has no
   * counterpart. There is no numeric-passthrough fallback: passing the id
   * through is what plays an unrelated sound.
   */
  public static OptionalInt translate(int fromProtocol, int toProtocol, int id) {
    if (fromProtocol == toProtocol) return OptionalInt.of(id);
    int from = registry(fromProtocol);
    int to = registry(toProtocol);
    if (from == 0 || to == 0) return OptionalInt.empty();
    if (from == to) return OptionalInt.of(id);
    int[] table = TABLES.get(key(from, to));
    if (table == null || id < 0 || id >= table.length) return OptionalInt.empty();
    int mapped = table[id];
    return mapped < 0 ? OptionalInt.empty() : OptionalInt.of(mapped);
  }

  public static int size(int protocol) {
    List<String> names = NAMES.get(registry(protocol));
    return names == null ? 0 : names.size();
  }

  private static long key(int from, int to) {
    return ((long) from << 32) | (to & 0xffffffffL);
  }

  private static Map<Integer, List<String>> loadAllNames() {
    Map<Integer, List<String>> names = new HashMap<>();
    for (int protocol : REGISTRIES) {
      names.put(protocol, loadNames("sounds_" + protocol + "_names.txt"));
    }
    return Map.copyOf(names);
  }

  private static Map<Integer, Map<String, Integer>> indexAll(Map<Integer, List<String>> names) {
    Map<Integer, Map<String, Integer>> ids = new HashMap<>();
    names.forEach((protocol, list) -> ids.put(protocol, index(list)));
    return Map.copyOf(ids);
  }

  private static Map<Long, int[]> loadAllTables() {
    Map<Long, int[]> tables = new HashMap<>();
    tables.put(key(393, 765), loadTable("sounds_393_to_765.bin"));
    tables.put(key(765, 393), loadTable("sounds_765_to_393.bin"));
    return Map.copyOf(tables);
  }

  private static Map<String, Integer> index(List<String> names) {
    Map<String, Integer> ids = new HashMap<>(names.size() * 2);
    for (int id = 0; id < names.size(); id++) {
      String name = names.get(id);
      if (!name.isEmpty()) ids.put(name, id);
    }
    return Map.copyOf(ids);
  }

  private static List<String> loadNames(String resource) {
    String path = "/gg/tame/conduit/protocol/sound/" + resource;
    try (InputStream in = SoundRegistries.class.getResourceAsStream(path)) {
      if (in == null) throw new IllegalStateException("missing resource " + path);
      List<String> names = new ArrayList<>();
      BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
      String line;
      while ((line = reader.readLine()) != null) names.add(line.trim());
      return List.copyOf(names);
    } catch (IOException exception) {
      throw new IllegalStateException("cannot load " + resource, exception);
    }
  }

  private static int[] loadTable(String resource) {
    String path = "/gg/tame/conduit/protocol/sound/" + resource;
    try (InputStream in = SoundRegistries.class.getResourceAsStream(path)) {
      if (in == null) throw new IllegalStateException("missing resource " + path);
      byte[] header = in.readNBytes(4);
      if (header.length != 4) throw new IllegalStateException("truncated " + resource);
      int length = (header[0] & 0xff) | ((header[1] & 0xff) << 8)
          | ((header[2] & 0xff) << 16) | ((header[3] & 0xff) << 24);
      if (length < 1 || length > 100_000) throw new IllegalStateException("bad length " + length);
      byte[] body = in.readNBytes(length * 4);
      if (body.length != length * 4) throw new IllegalStateException("truncated body " + resource);
      int[] table = new int[length];
      for (int index = 0; index < length; index++) {
        int offset = index * 4;
        table[index] = (body[offset] & 0xff) | ((body[offset + 1] & 0xff) << 8)
            | ((body[offset + 2] & 0xff) << 16) | ((body[offset + 3] & 0xff) << 24);
      }
      return table;
    } catch (IOException exception) {
      throw new IllegalStateException("cannot load " + resource, exception);
    }
  }
}
